apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-b
  template:
    metadata:
      labels:
        app: backend-b
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/toybox/mc-backend:v1
          imagePullPolicy: Always
          name: backend-b
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "v1"
            - name: KIND
              value: "backend-b"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-b
  type: ClusterIP
  clusterIP: None
---